Presentation/Retaguarda.Web/Areas/Clientes/Controllers/TipoIdentificacaoController.cs
using FileSys.Retaguarda.Application.Admin.Interface;
using FileSys.Retaguarda.Application.Admin.ViewModel;
using FiveSys.Presentation.Retaguarda.Web.Helpers;
using FiveSys.Retaguarda.Core.Domain.Acesso.Enum;
using Microsoft.AspNetCore.Mvc;

namespace Retaguarda.Web.Areas.Clientes.Controllers
{
    [Area("Clientes")]
    public class TipoIdentificacaoController : Controller
    {
        private readonly ITipoIdentificacaoAppService service;

        public TipoIdentificacaoController(ITipoIdentificacaoAppService service)
        {
            this.service = service;

        }

        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Acessar)]
        public IActionResult Index()
        {
            var resultado = service.RecuperarTodos().Data;

            return View(resultado);
        }

        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Cadastrar)]
        public IActionResult Cadastrar(string areaId)
        {
            var model = new TipoIdentificacaoViewModel();
            return View("Form", model);
        }

        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Acessar)]
        public IActionResult Visualizar(string id)
        {
            var resultado = service.RecuperarPorId(id);

            var model = resultado.Data;
            model.SomenteLeitura = true;

            return View("Form", model);
        }

        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Editar)]
        public IActionResult Editar(string id)
        {
            var resultado = service.RecuperarPorId(id);

            var model = resultado.Data;

            return View("Form", model);
        }

        [HttpPost]
        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Cadastrar)]
        public IActionResult Cadastrar(TipoIdentificacaoViewModel model)
        {
            var resultado = service.Inserir(model);

            if (resultado.Successo)
                resultado.RedirecionarPara(Url.Action(nameof(Index)));

            return Json(resultado.Retorno());
        }

        [HttpPost]
        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Editar)]
        public IActionResult Editar(TipoIdentificacaoViewModel model)
        {
            var resultado = service.Atualizar(model);

            if (resultado.Successo)
                resultado.RedirecionarPara(Url.Action(nameof(Index)));

            return Json(resultado.Retorno());
        }

        [HttpPost]
        [TemPermissao(FuncionalidadeEnum.TipoIdentificacao, AcaoEnum.Excluir)]
        public IActionResult Excluir(string id)
        {
            var resultado = service.RemoverPorId(id);

            if (resultado.Successo)
                resultado.RedirecionarPara(Url.Action(nameof(Index)));

            return Json(resultado.Retorno());
        }
    }
}

Presentation/Retaguarda.Web/Views/Shared/_Breadcrumb.cshtml
@{
    string action = (string)base.ViewContext.RouteData.Values["action"];
    string controller = (string)base.ViewContext.RouteData.Values["controller"];
    string area = (string)base.ViewContext.RouteData.DataTokens["area"];
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@controller</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home", new { area = ""})">Página Inicial</a>
            </li>
            @if (!string.IsNullOrEmpty(area))
            {
                <li>
                    @area
                </li>
            }
            <li>
                <a href="@Url.Action("Index", controller)">@controller</a>
            </li>
            <li class="active">
                <strong>@(action == "Index" ? "Lista" : action)</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

Presentation/Retaguarda.Web/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> FileSys &copy; 2014 - 2017
    </div>
</div>

Presentation/Retaguarda.Web/Views/Shared/_Layout.cshtml
@{
    string controller = (string)base.ViewContext.RouteData.Values["controller"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@controller - Retaguarda</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/lib/metisMenu/dist/metisMenu.css" rel="stylesheet" />
        <link href="~/css/animate.css" rel="stylesheet" />
        <link href="~/lib/datatables.net-dt/css/jquery.dataTables.css" rel="stylesheet" />
        <link href="~/lib/toastr/toastr.css" rel="stylesheet" />
        <link href="~/lib/jquery-confirm2/css/jquery-confirm.css" rel="stylesheet" />
        <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker.css" rel="stylesheet" />
        <link href="~/lib/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet" />
        <link href="~/lib/select2/dist/css/select2.css" rel="stylesheet" />
        <link href="~/css/style.css" asp-append-version="true" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/lib/metisMenu/dist/metisMenu.min.css" rel="stylesheet" />
        <link href="~/css/animate.css" rel="stylesheet" />
        <link href="~/lib/datatables.net-dt/css/jquery.dataTables.css" rel="stylesheet" />
        <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
        <link href="~/lib/jquery-confirm2/css/jquery-confirm.css" rel="stylesheet" />
        <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
        <link href="~/lib/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet" />
        <link href="~/lib/select2/dist/css/select2.css" rel="stylesheet" />
        <link href="~/css/style.css" asp-append-version="true" rel="stylesheet" />
        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
</head>
<body class="skin-3">

    <!-- Wrapper-->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Breadcrumb -->
            @Html.Partial("_Breadcrumb")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/metisMenu/dist/metisMenu.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/datatables.net/js/jquery.dataTables.js"></script>
        <script src="~/lib/datatables.net-bs/js/dataTables.bootstrap.js"></script>
        <script src="~/lib/datatables.net-buttons/js/dataTables.buttons.js"></script>
        <script src="~/lib/datatables.net-buttons-bs/js/buttons.bootstrap.js"></script>
        <script src="~/lib/pdfmake/build/pdfmake.js"></script>
        <script src="~/lib/pdfmake/build/vfs_fonts.js"></script>
        <script src="~/lib/jszip/dist/jszip.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.colVis.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.flash.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.html5.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.print.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/jquery.blockui/jquery.blockUI.js"></script>
        <script src="~/lib/jquery-confirm2/js/jquery-confirm.js"></script>
        <script src="~/lib/jquery-form/src/jquery.form.js"></script>
        <script src="~/lib/toastr/toastr.js"></script>
        <script src="~/lib/jquery-mask-plugin/dist/jquery.mask.js"></script>
        <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
        <script src="~/lib/bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="~/lib/select2/dist/js/select2.js"></script>

        <!--framework-->
        <script src="~/js/framework/fw-blockui.js"></script>
        <script src="~/js/framework/fw-form.js"></script>
        <script src="~/js/framework/fw-alert.js"></script>
        <script src="~/js/framework/fw-delete-item.js"></script>
        <script src="~/js/framework/fw-modal.js"></script>
        <script src="~/js/framework/fw-load-by-field.js"></script>

        <script src="~/js/script.js"></script>
        <script src="~/lib/pace/pace.js"></script>
        <script src="~/js/site.js"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/metisMenu/dist/metisMenu.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/datatables.net/js/jquery.dataTables.js"></script>
        <script src="~/lib/datatables.net-bs/js/dataTables.bootstrap.js"></script>
        <script src="~/lib/datatables.net-buttons/js/dataTables.buttons.js"></script>
        <script src="~/lib/datatables.net-buttons-bs/js/buttons.bootstrap.js"></script>
        <script src="~/lib/pdfmake/build/pdfmake.js"></script>
        <script src="~/lib/pdfmake/build/vfs_fonts.js"></script>
        <script src="~/lib/jszip/dist/jszip.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.colVis.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.flash.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.html5.js"></script>
        <script src="~/lib/datatables.net-buttons/js/buttons.print.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/jquery.blockui/jquery.blockUI.js"></script>
        <script src="~/lib/jquery-confirm2/js/jquery-confirm.js"></script>
        <script src="~/lib/jquery-form/src/jquery.form.js"></script>
        <script src="~/lib/toastr/toastr.js"></script>
        <script src="~/lib/jquery-mask-plugin/dist/jquery.mask.js"></script>
        <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
        <script src="~/lib/bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="~/lib/select2/dist/js/select2.js"></script>

        <!--framework-->
        <script src="~/js/framework/fw-blockui.js"></script>
        <script src="~/js/framework/fw-form.js"></script>
        <script src="~/js/framework/fw-alert.js"></script>
        <script src="~/js/framework/fw-delete-item.js"></script>
        <script src="~/js/framework/fw-modal.js"></script>
        <script src="~/js/framework/fw-load-by-field.js"></script>

        <script src="~/js/script.js"></script>
        <script src="~/lib/pace/pace.js"></script>
        <script src="~/js/site.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Presentation/Retaguarda.Web/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="~/img/user.png">
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="text-muted text-xs block"><strong class="font-bold">Example user</strong> <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">Sair</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    <span style="color: #ff8400">FIVE</span><span style="color: #000">SYS</span>
                </div>
            </li>
            <li class="@Html.IsSelected(area: "Admin")">
                <a href="index.html"><i class="fa fa-cog"></i> <span class="nav-label">Administração</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="@Html.IsSelected(controller: "Parametro")"><a href="@Url.Action("Index", "Parametro", new { area = "admin"})">Parâmetro</a></li>
                    <li class="@Html.IsSelected(controller: "Ramo")"><a href="@Url.Action("Index", "Ramo", new { area = "admin"})">Ramo</a></li>
                    <li class="@Html.IsSelected(controller: "Industria")"><a href="@Url.Action("Index", "Industria", new { area = "admin"})">Indústria</a></li>
                    <li class="@Html.IsSelected(controller: "Usuario")"><a href="@Url.Action("Index", "Usuario", new { area = "admin"})">Usuário</a></li>
                    <li class="@Html.IsSelected(controller: "Perfil")"><a href="@Url.Action("Index", "Perfil", new { area = "acesso"})">Perfil</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(area: "Clientes")">
                <a href="#"><i class="fa fa-handshake-o"></i> <span class="nav-label">Cliente</span> <span class="fa arrow"></span></a>

                <ul class="nav nav-second-level collapse">
                    <li class="@Html.IsSelected(controller: "Cliente")"><a href="@Url.Action("Index", "Cliente", new { area = "Clientes"})">Cliente</a></li>
                    <li class="@Html.IsSelected(controller: "TipoCliente")"><a href="@Url.Action("Index", "TipoCliente", new { area = "Clientes"})">Tipo de Cliente</a></li>
                    <li class="@Html.IsSelected(controller: "TipoIdenditicacao")"><a href="@Url.Action("Index", "TipoIdentificacao", new { area = "Clientes"})">Tipo de Identificação</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(area: "Lojas")">
                <a href="#"><i class="fa fa-building"></i> <span class="nav-label">Loja</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="@Html.IsSelected(controller: "Loja")"><a href="@Url.Action("Index", "Loja", new { area = "Lojas"})">Loja</a></li>
                </ul>
            </li>

            <li class="@Html.IsSelected(area: "Produtos")">
                <a href="#"><i class="fa fa-barcode"></i> <span class="nav-label">Produtos</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li class="@Html.IsSelected(controller: "Fornecedor")"><a href="@Url.Action("Index", "Fornecedor", new { area = "Produtos"})">Fornecedor</a></li>
                    <li class="@Html.IsSelected(controller: "Marca")"><a href="@Url.Action("Index", "Marca", new { area = "Produtos"})">Marca/Fabricante</a></li>
                    <li class="@Html.IsSelected(controller: "Tara")"><a href="@Url.Action("Index", "Tara", new { area = "Produtos"})">Tara</a></li>
                    <li class="@Html.IsSelected(controller: "TipoProduto")"><a href="@Url.Action("Index", "TipoProduto", new { area = "Produtos"})">Tipos de Produtos</a></li>
                    <li class="@Html.IsSelected(controller: "TipoPreco")"><a href="@Url.Action("Index", "TipoPreco", new { area = "Produtos"})">Tipos de Preço</a></li>
                    <li class="@Html.IsSelected(controller: "Unidade")"><a href="@Url.Action("Index", "Unidade", new { area = "Produtos"})">Unidade</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

Presentation/Retaguarda.Web/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            @*<form role="search" class="navbar-form-custom" method="post" action="">
                    <div class="form-group">
                        <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                    </div>
                </form>*@
        </div>
        @Html.Partial("_LoginPartial")
    </nav>
</div>